# -*- coding: utf-8 -*-
"""SentimentAnalysisonProducts

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MIyiAlRoeXyLpAr6MHT4wI9qpM9wuirD
"""

import pandas as pd

df = pd.read_csv("walmart_product_review_file.csv")
print(df.head())
df.info()

# Missing value percentage
missing_percentage = (df.isnull().sum() / len(df)) * 100
missing_percentage.sort_values(ascending=False)

drop_cols = [
    'Dataset Origin', 'Product Barcode', 'Match Rank', 'Match Score',
    'Match Type', 'Sku', 'Upc', 'Product Model Number',
    'Product Contents', 'Bsr'
]

df_clean = df.drop(columns=drop_cols)

print(df_clean.shape)

nlp_df = df_clean[[
    'Product Name',
    'Product Description',
    'Product Tags',
    'Product Category',
    'Product Brand',
    'Product Rating',
    'Product Reviews Count'
]]

nlp_df.head()

# Rating distribution
nlp_df['Product Rating'].value_counts().sort_index()
print(nlp_df.shape)
print(nlp_df.head())

# Rows with available review count
nlp_df[nlp_df['Product Reviews Count'].notnull()][
    ['Product Name', 'Product Reviews Count']
].head(10)

#Dropping rows with NAN reviews
nlp_df = nlp_df.dropna(subset=['Product Reviews Count'])

print(nlp_df.shape)

# Confirm no missing values remain
nlp_df[['Product Reviews Count', 'Product Rating']].isnull().sum()

nlp_df = nlp_df.dropna(subset=['Product Rating'])

print(nlp_df.shape)

# Confirm no missing values remain
nlp_df[['Product Reviews Count', 'Product Rating']].isnull().sum()

"""| Product Rating | Sentiment Label |
| -------------- | --------------- |
| 1 – 2          | Negative        |
| 3              | Neutral         |
| 4 – 5          | Positive        |

"""

#Sentiment Column
def map_sentiment(rating):
    if rating <= 2:
        return 'Negative'
    elif rating == 3:
        return 'Neutral'
    else:
        return 'Positive'

nlp_df['Sentiment'] = nlp_df['Product Rating'].apply(map_sentiment)

# Preview
nlp_df[['Product Rating', 'Sentiment']].head(10)

#Sentiment Distribution
nlp_df['Sentiment'].value_counts()

import matplotlib.pyplot as plt

nlp_df['Sentiment'].value_counts().plot(kind='bar')
plt.xlabel('Sentiment')
plt.ylabel('Number of Samples')
plt.title('Sentiment Distribution')
plt.show()

import random

positive_reviews = [
    "Excellent product, exceeded my expectations.",
    "Very happy with the quality and performance.",
    "Worth the money, highly recommended.",
    "The product works perfectly and feels premium.",
    "Amazing experience, will buy again.",
    "Great quality and fast delivery.",
    "Satisfied with the purchase, no complaints.",
    "Good value for money and reliable performance.",
    "The product quality is top-notch and very durable.",
    "Absolutely love this product, performs as described.",
    "Highly impressed with the design and functionality.",
    "Very reliable and performs consistently well.",
    "The product arrived on time and works flawlessly.",
    "Build quality is excellent and feels sturdy.",
    "This product delivers great performance for daily use.",
    "Easy to use and gives consistent results.",
    "One of the best purchases I have made recently.",
    "The product quality exceeded my expectations.",
    "Very satisfied with the overall experience.",
    "Great product, works exactly as advertised.",
    "Smooth performance and excellent build quality.",
    "Highly recommended for anyone looking for quality.",
    "The product performs well and feels premium.",
    "Excellent value for the price paid.",
    "Really happy with this purchase, no issues so far."
]

neutral_reviews = [
    "The product is okay for the price.",
    "Average quality, nothing special.",
    "Does the job but could be improved.",
    "Neither good nor bad, acceptable performance.",
    "It's fine but not outstanding.",
    "Meets basic expectations.",
    "The product works as expected but nothing more.",
    "Decent product, but there are better options available.",
    "Quality is average considering the price.",
    "Not bad, but I was expecting slightly better performance.",
    "The product is usable but has some minor issues.",
    "Overall experience is satisfactory.",
    "It performs okay but lacks premium features.",
    "The product is fine for regular use.",
    "Acceptable quality but not impressive.",
    "Serves its purpose, nothing exceptional.",
    "The product is okay, but improvements are needed.",
    "Fair quality, matches the description.",
    "Reasonable product for the given price range.",
    "Neither disappointed nor impressed with this product.",
    "The product functions properly but does not stand out.",
    "Performance is average compared to similar products.",
    "Suitable for basic usage, nothing more.",
    "The product meets minimum requirements.",
    "It works fine, but feels quite ordinary."
]

negative_reviews = [
    "Very disappointed with the quality.",
    "Not worth the money at all.",
    "Poor performance and bad build quality.",
    "Stopped working after a short time.",
    "Would not recommend this product.",
    "Low quality, waste of money.",
    "Bad experience overall.",
    "The product did not meet my expectations.",
    "Quality is very poor and disappointing.",
    "The product arrived damaged and unusable.",
    "Completely dissatisfied with this purchase.",
    "Does not work as advertised.",
    "Extremely poor quality, regret buying it.",
    "The product failed after just a few uses.",
    "Very bad build quality and performance.",
    "Not satisfied, would not buy again.",
    "The product feels cheap and unreliable.",
    "Terrible experience, not recommended at all.",
    "The product has many defects and issues.",
    "Worst purchase experience so far.",
    "The product quality is unacceptable.",
    "Frequent issues and poor reliability.",
    "The product stopped functioning properly.",
    "Very unhappy with this purchase.",
    "Not worth the price paid."
]

def assign_review_from_rating(rating):
    if rating <= 2:
        return random.choice(negative_reviews)
    elif rating == 3:
        return random.choice(neutral_reviews)
    else:
        return random.choice(positive_reviews)

nlp_df['User_Review_Text'] = nlp_df['Product Rating'].apply(assign_review_from_rating)
nlp_df[['Product Rating', 'User_Review_Text']].head(15)

# Loop through each sentiment category
for sentiment in ['Positive', 'Neutral', 'Negative']:

    # Print sentiment heading
    print(f"\n--- {sentiment} Reviews ---")

    # Filter dataset by sentiment, select rating and review text,
    # randomly sample 5 rows, and print without index
    print(
        nlp_df[nlp_df['Sentiment'] == sentiment][
            ['Product Rating', 'User_Review_Text']
        ]
        .sample(5, random_state=42)
        .to_string(index=False)
    )

# Calculate character length of each user review
nlp_df['review_char_length'] = nlp_df['User_Review_Text'].apply(len)

# Display basic statistics of character length
nlp_df['review_char_length'].describe()

# Calculate word count for each review
nlp_df['review_word_count'] = nlp_df['User_Review_Text'].apply(lambda x: len(x.split()))

# Display basic statistics of word count
nlp_df['review_word_count'].describe()

# Group by sentiment and calculate average word count
nlp_df.groupby('Sentiment')['review_word_count'].mean()

import matplotlib.pyplot as plt

# Plot histogram of review word counts
plt.figure()
nlp_df['review_word_count'].hist(bins=20)
plt.xlabel("Number of Words in Review")
plt.ylabel("Frequency")
plt.title("Distribution of Review Word Count")
plt.show()

# Import required libraries for text preprocessing
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

# Download required NLTK resources
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

# Initialize stopwords and lemmatizer
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

# Function to clean and preprocess text
def preprocess_text(text):

    # Convert text to lowercase
    text = text.lower()

    # Remove numbers and special characters
    text = re.sub(r'[^a-z\s]', '', text)

    # Tokenize text and remove stopwords
    tokens = [word for word in text.split() if word not in stop_words]

    # Lemmatize tokens
    tokens = [lemmatizer.lemmatize(word) for word in tokens]

    # Join tokens back into a single string
    return " ".join(tokens)

# Apply preprocessing to user review text
nlp_df['Clean_Review_Text'] = nlp_df['User_Review_Text'].apply(preprocess_text)

# Preview cleaned text
nlp_df[['User_Review_Text', 'Clean_Review_Text']].head(5)

pip install wordcloud

# Import WordCloud and matplotlib
from wordcloud import WordCloud
import matplotlib.pyplot as plt

# Combine all cleaned reviews into a single string
all_reviews_text = " ".join(nlp_df['Clean_Review_Text'])

# Generate word cloud
wordcloud = WordCloud(
    width=800,
    height=400,
    background_color='white'
).generate(all_reviews_text)

# Plot the word cloud
plt.figure()
plt.imshow(wordcloud)
plt.axis('off')
plt.title("Word Cloud for All Reviews")
plt.show()

# Generate word clouds for each sentiment
for sentiment in ['Positive', 'Neutral', 'Negative']:

    # Combine cleaned reviews for the given sentiment
    sentiment_text = " ".join(
        nlp_df[nlp_df['Sentiment'] == sentiment]['Clean_Review_Text']
    )

    # Generate word cloud
    wordcloud = WordCloud(
        width=800,
        height=400,
        background_color='white'
    ).generate(sentiment_text)

    # Plot word cloud
    plt.figure()
    plt.imshow(wordcloud)
    plt.axis('off')
    plt.title(f"Word Cloud for {sentiment} Reviews")
    plt.show()

# Create sentiment-to-label mapping
sentiment_mapping = {
    'Negative': 0,
    'Neutral': 1,
    'Positive': 2
}

# Apply encoding
nlp_df['Sentiment_Label'] = nlp_df['Sentiment'].map(sentiment_mapping)

# Verify encoding
nlp_df[['Sentiment', 'Sentiment_Label']].head(10)

# Check if any rows failed to map
nlp_df['Sentiment_Label'].isnull().sum()

# Check class distribution after encoding
nlp_df['Sentiment_Label'].value_counts()

# Import train-test split utility
from sklearn.model_selection import train_test_split
# Define input text (raw reviews)
X = nlp_df['User_Review_Text'].values

# Define target labels (encoded sentiment)
y = nlp_df['Sentiment_Label'].values

# Split dataset into training and testing sets
# stratify=y keeps sentiment class balance
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

# Print dataset sizes
print("Training samples:", len(X_train))
print("Testing samples:", len(X_test))

pip install transformers torch

# Import BERT tokenizer
from transformers import BertTokenizer
# Load BERT base uncased tokenizer
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

# Tokenize training data
train_encodings = tokenizer(
    list(X_train),
    truncation=True,
    padding=True,
    max_length=64,
    return_tensors='pt'
)

# Tokenize testing data
test_encodings = tokenizer(
    list(X_test),
    truncation=True,
    padding=True,
    max_length=64,
    return_tensors='pt'
)

# Import PyTorch utilities
import torch
from torch.utils.data import Dataset

# Custom Dataset class for BERT
class ReviewDataset(Dataset):

    def __init__(self, encodings, labels):
        # Store tokenized inputs and labels
        self.encodings = encodings
        self.labels = labels

    def __len__(self):
        # Return dataset size
        return len(self.labels)

    def __getitem__(self, idx):
        # Fetch input item at index
        item = {key: val[idx] for key, val in self.encodings.items()}

        # Add label tensor
        item['labels'] = torch.tensor(self.labels[idx])

        return item

# Create training and testing datasets
train_dataset = ReviewDataset(train_encodings, y_train)
test_dataset = ReviewDataset(test_encodings, y_test)

pip install transformers

# Import PyTorch core libraries
import torch
from torch.utils.data import DataLoader

# Import BERT model for sequence classification
from transformers import BertForSequenceClassification

# Import optimizer from PyTorch
from torch.optim import AdamW

# Import learning rate scheduler from transformers
from transformers import get_linear_schedule_with_warmup

# Check if GPU is available, else use CPU
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Print device being used
print("Using device:", device)

# Load BERT model with 3 output classes (Negative, Neutral, Positive)
model = BertForSequenceClassification.from_pretrained(
    'bert-base-uncased',
    num_labels=3
)

# Move model to selected device
model.to(device)

# Define batch size
BATCH_SIZE = 8

# Create DataLoader for training data
train_loader = DataLoader(
    train_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True
)

# Create DataLoader for testing data
test_loader = DataLoader(
    test_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False
)

# Define AdamW optimizer
optimizer = AdamW(
    model.parameters(),
    lr=2e-5,
    eps=1e-8
)

# Total number of training steps
total_steps = len(train_loader) * 3  # 3 epochs

# Learning rate scheduler
scheduler = get_linear_schedule_with_warmup(
    optimizer,
    num_warmup_steps=0,
    num_training_steps=total_steps
)

# Set number of epochs
EPOCHS = 2

# Loop through epochs
for epoch in range(EPOCHS):

    print(f"\nEpoch {epoch + 1}/{EPOCHS}")

    # Set model to training mode
    model.train()

    total_loss = 0

    # Loop through training batches
    for batch in train_loader:

        # Clear gradients
        optimizer.zero_grad()

        # Move batch data to device
        input_ids = batch['input_ids'].to(device)
        attention_mask = batch['attention_mask'].to(device)
        labels = batch['labels'].to(device)

        # Forward pass
        outputs = model(
            input_ids=input_ids,
            attention_mask=attention_mask,
            labels=labels
        )

        # Extract loss
        loss = outputs.loss

        # Backpropagation
        loss.backward()

        # Update optimizer and scheduler
        optimizer.step()
        scheduler.step()

        # Accumulate loss
        total_loss += loss.item()

    # Calculate average loss
    avg_loss = total_loss / len(train_loader)

    # Print epoch loss
    print("Training Loss:", avg_loss)

# Import evaluation metrics
from sklearn.metrics import accuracy_score, classification_report
import numpy as np

# Set model to evaluation mode
model.eval()

# Lists to store predictions and true labels
predictions = []
true_labels = []

# Disable gradient calculation for evaluation
with torch.no_grad():

    # Loop through test batches
    for batch in test_loader:

        # Move batch to device
        input_ids = batch['input_ids'].to(device)
        attention_mask = batch['attention_mask'].to(device)
        labels = batch['labels'].to(device)

        # Forward pass
        outputs = model(
            input_ids=input_ids,
            attention_mask=attention_mask
        )

        # Get predicted class
        logits = outputs.logits
        preds = torch.argmax(logits, dim=1)

        # Store predictions and labels
        predictions.extend(preds.cpu().numpy())
        true_labels.extend(labels.cpu().numpy())

# Print accuracy score
print("Accuracy:", accuracy_score(true_labels, predictions)*100)

# Print detailed classification report
print(classification_report(
    true_labels,
    predictions,
    target_names=['Negative', 'Neutral', 'Positive']
))

# Function to predict sentiment for a single review
def predict_sentiment(review_text):

    # Tokenize input review
    encoding = tokenizer(
        review_text,
        truncation=True,
        padding=True,
        max_length=64,
        return_tensors='pt'
    )

    # Move tensors to device
    input_ids = encoding['input_ids'].to(device)
    attention_mask = encoding['attention_mask'].to(device)

    # Disable gradient calculation
    with torch.no_grad():
        outputs = model(
            input_ids=input_ids,
            attention_mask=attention_mask
        )

    # Get predicted class index
    predicted_label = torch.argmax(outputs.logits, dim=1).item()

    # Map numeric label back to sentiment
    label_mapping = {
        0: "Negative",
        1: "Neutral",
        2: "Positive"
    }

    # Return sentiment
    return label_mapping[predicted_label]

# Infinite loop for interactive sentiment prediction
while True:

    # Take user input from keyboard
    user_review = input("\nEnter a product review (or type 'exit' to stop): ")

    # Exit condition
    if user_review.lower() == 'exit':
        print("Exiting sentiment prediction.")
        break

    # Predict sentiment using trained BERT model
    sentiment = predict_sentiment(user_review)

    # Display result
    print("Predicted Sentiment:", sentiment)



# Mixed sentiment review templates (realistic ambiguity)
mixed_reviews = [
    "The product quality is good but the price is too high.",
    "Works fine, but the delivery was delayed.",
    "Good performance, although customer support is poor.",
    "The product is average, not worth the hype.",
    "Bad packaging, but the item itself works well.",
    "Decent quality but has some annoying issues.",
    "Product is okay, but I expected better for this price.",
    "Not terrible, but not impressive either.",
    "The product functions properly, but build quality is weak.",
    "Satisfied with performance, disappointed with durability."
]

# Import random module
import random

# Assign mostly neutral labels to mixed reviews
mixed_sentiments = ['Neutral', 'Neutral', 'Positive', 'Negative']

# Create DataFrame for noisy reviews
mixed_df = pd.DataFrame({
    'User_Review_Text': random.choices(mixed_reviews, k=300),
    'Sentiment': random.choices(mixed_sentiments, k=300)
})

# Encode sentiment labels numerically
mixed_df['Sentiment_Label'] = mixed_df['Sentiment'].map({
    'Negative': 0,
    'Neutral': 1,
    'Positive': 2
})

# Combine original dataset with noisy reviews
nlp_df_augmented = pd.concat(
    [nlp_df[['User_Review_Text', 'Sentiment', 'Sentiment_Label']], mixed_df],
    ignore_index=True
)

# Shuffle dataset to avoid ordering bias
nlp_df_augmented = nlp_df_augmented.sample(frac=1, random_state=42).reset_index(drop=True)

# Check new dataset size
print("New dataset size:", nlp_df_augmented.shape)

# Check sentiment distribution after augmentation
nlp_df_augmented['Sentiment'].value_counts()

# Update inputs and labels
X = nlp_df_augmented['User_Review_Text'].values
y = nlp_df_augmented['Sentiment_Label'].values

"""RETRAINING BERT MODEL

"""

# Import train-test split
from sklearn.model_selection import train_test_split

# Define features and labels
X = nlp_df_augmented['User_Review_Text'].values
y = nlp_df_augmented['Sentiment_Label'].values

# Perform stratified split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

# Print dataset sizes
print("Train size:", len(X_train))
print("Test size:", len(X_test))

# Import tokenizer
from transformers import BertTokenizer
# Load BERT tokenizer
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
# Tokenize training data
train_encodings = tokenizer(
    list(X_train),
    truncation=True,
    padding=True,
    max_length=64,
    return_tensors='pt'
)

# Tokenize testing data
test_encodings = tokenizer(
    list(X_test),
    truncation=True,
    padding=True,
    max_length=64,
    return_tensors='pt'
)

# Import torch utilities
import torch
from torch.utils.data import Dataset

# Custom dataset class
class ReviewDataset(Dataset):

    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        item = {key: val[idx] for key, val in self.encodings.items()}
        item['labels'] = torch.tensor(self.labels[idx])
        return item

# Create dataset objects
train_dataset = ReviewDataset(train_encodings, y_train)
test_dataset = ReviewDataset(test_encodings, y_test)

# Import required libraries
from transformers import BertForSequenceClassification
from torch.utils.data import DataLoader
from torch.optim import AdamW
from transformers import get_linear_schedule_with_warmup

# Select device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)
# Load BERT model for 3-class classification
model = BertForSequenceClassification.from_pretrained(
    'bert-base-uncased',
    num_labels=3
)

# Move model to device
model.to(device)

# Define batch size
BATCH_SIZE = 8

# Create dataloaders
train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=BATCH_SIZE, shuffle=False)

# Define optimizer
optimizer = AdamW(model.parameters(), lr=2e-5)
# Total training steps
EPOCHS = 2
total_steps = len(train_loader) * EPOCHS

# Learning rate scheduler
scheduler = get_linear_schedule_with_warmup(
    optimizer,
    num_warmup_steps=0,
    num_training_steps=total_steps
)

# Training loop
for epoch in range(EPOCHS):

    print(f"\nEpoch {epoch + 1}/{EPOCHS}")
    model.train()
    total_loss = 0

    for batch in train_loader:

        optimizer.zero_grad()

        input_ids = batch['input_ids'].to(device)
        attention_mask = batch['attention_mask'].to(device)
        labels = batch['labels'].to(device)

        outputs = model(
            input_ids=input_ids,
            attention_mask=attention_mask,
            labels=labels
        )

        loss = outputs.loss
        loss.backward()

        optimizer.step()
        scheduler.step()

        total_loss += loss.item()

    print("Training Loss:", total_loss / len(train_loader))

# Import evaluation metrics
from sklearn.metrics import accuracy_score, classification_report
import numpy as np

# Set model to evaluation mode
model.eval()

predictions = []
true_labels = []

with torch.no_grad():
    for batch in test_loader:

        input_ids = batch['input_ids'].to(device)
        attention_mask = batch['attention_mask'].to(device)
        labels = batch['labels'].to(device)

        outputs = model(
            input_ids=input_ids,
            attention_mask=attention_mask
        )

        preds = torch.argmax(outputs.logits, dim=1)

        predictions.extend(preds.cpu().numpy())
        true_labels.extend(labels.cpu().numpy())

# Print final accuracy
print("Final Accuracy:", accuracy_score(true_labels, predictions)*100)

# Print detailed classification report
print(classification_report(
    true_labels,
    predictions,
    target_names=['Negative', 'Neutral', 'Positive']
))

# Import os module for directory handling
import os

# Define directory to save model
MODEL_DIR = "bert_sentiment_model"

# Create directory if it does not exist
os.makedirs(MODEL_DIR, exist_ok=True)

# Save trained BERT model weights
model.save_pretrained(MODEL_DIR)

# Save tokenizer files
tokenizer.save_pretrained(MODEL_DIR)

# Confirmation message
print("Model and tokenizer saved successfully!")

# Function to predict sentiment for a single review
def predict_sentiment(review_text):

    # Tokenize input review
    encoding = tokenizer(
        review_text,
        truncation=True,
        padding=True,
        max_length=64,
        return_tensors='pt'
    )

    # Move tensors to device
    input_ids = encoding['input_ids'].to(device)
    attention_mask = encoding['attention_mask'].to(device)

    # Disable gradient calculation
    with torch.no_grad():
        outputs = model(
            input_ids=input_ids,
            attention_mask=attention_mask
        )

    # Get predicted class index
    predicted_label = torch.argmax(outputs.logits, dim=1).item()

    # Map numeric label back to sentiment
    label_mapping = {
        0: "Negative",
        1: "Neutral",
        2: "Positive"
    }

    # Return sentiment
    return label_mapping[predicted_label]

# Infinite loop for interactive sentiment prediction
while True:

    # Take user input from keyboard
    user_review = input("\nEnter a product review (or type 'exit' to stop): ")

    # Exit condition
    if user_review.lower() == 'exit':
        print("Exiting sentiment prediction.")
        break

    # Predict sentiment using trained BERT model
    sentiment = predict_sentiment(user_review)

    # Display result
    print("Predicted Sentiment:", sentiment)

# Import os module
import os

# Define model save directory in Colab
MODEL_DIR = "/content/bert_sentiment_model"

# Create directory if it does not exist
os.makedirs(MODEL_DIR, exist_ok=True)

# Save trained BERT model
model.save_pretrained(MODEL_DIR)

# Save tokenizer
tokenizer.save_pretrained(MODEL_DIR)

# Confirm save
print("Model saved to Colab successfully!")

# Zip the model folder for download
!zip -r bert_sentiment_model.zip bert_sentiment_model